version: '3'
services:
  tf:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./content/wheels:/wheels
      - ./content/tensorflow:/tensorflow
    environment:
      - PYTHON_VERSION=${PYTHON_VERSION-3.6}
