version: '3'
services:
  tf:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./artifacts/wheels:/artifacts/wheels
      - ./artifacts/tensorflow:/artifacts/tensorflow
    environment:
      - PYTHON_VERSION=${PYTHON_VERSION-3.6}
